name: Apply for and Intership program OSL
description: Request Form for new interns
title: "New Intern: <Insert your name>"
labels: [new-intern]
assignees: EverVino, xmnlab
body:
  - type: markdown
    attributes:
      value: |
        To apply for the internship please fill out the following form:
        Notas:
        - Our Community on discord: https://opensciencelabs.org/discord

  - type: input
    id: email
    attributes:
      label: E-mail
      description: E-mail
      placeholder: ej. email@example.com
    validations:
      required: true

  - type: input
    id: name-full
    attributes:
      label: Full Name
      description: Full Name
    validations:
      required: true

  - type: input
    id: url-linkedin
    attributes:
      label: URL perfil Linkedin
      description: URL del perfil en Linkedin
    validations:
      required: false

  - type: textarea
    id: bio
    attributes:
      label: Bio
      description: A brief summary about yourself, similar to the one you have in the summary of your CV or LinkedIn profile.
    validations:
      required: true
  

  - type: checkboxes
    id: cv-send
    attributes:
      label: Send your CV
      description: We want to have your CV in our database. Please send it to opensciencelabs@gmail.com in pdf format.
      options:
        - label: I have sent my CV to opensciencelabs@gmail.com
          required: true
  - type: checkboxes
    id: fields-knowledge
    attributes:
      label: What projects are you interested in?
      description:  Mark the projects you would be most interested in contributing to. You can mark multiple projects. To get more info about project go to https://opensciencelabs.org/programs/internship/
      options:
        - label: scicookie
        - label: makim
          

  - type: checkboxes
    id: coc-accepting
    attributes:
      label: Code of Conduct
      description: Accept the Code of Conduct
      options:
        - label: I have read the [Code of Conduct](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo
          required: true

