name: Apply for an Intership program OSL
description: Request Form for new interns
title: "New Intern: <Insert your name>"
labels: [new-intern]
assignees: EverVino, xmnlab
body:
  - type: markdown
    attributes:
      value: |
        To apply for the internship please fill out the following form:
        Notas:
        - Our Community on discord: https://opensciencelabs.org/discord

  - type: input
    id: email
    attributes:
      label: E-mail
      description: E-mail
      placeholder: ej. email@example.com
    validations:
      required: true

  - type: input
    id: name-full
    attributes:
      label: Full Name
      description: Full Name
    validations:
      required: true

  - type: input
    id: url-linkedin
    attributes:
      label: URL perfil Linkedin
      description: URL del perfil en Linkedin
    validations:
      required: false

  - type: textarea
    id: bio
    attributes:
      label: Bio
      description: A brief summary about yourself, similar to the one you have in the summary of your CV or LinkedIn profile.
    validations:
      required: true
  

  - type: checkboxes
    id: cv-send
    attributes:
      label: Send your CV
      description: We want to have your CV in our database. Please send it to opensciencelabs@gmail.com in pdf format.
      options:
        - label: I have sent my CV to opensciencelabs@gmail.com
    validations:
      required: true

  - type: checkboxes
    id: fields-knowledge
    attributes:
      label: What projects are you interested in?
      description:  Mark the projects you would be most interested in contributing to. You can mark multiple projects. To get more info about project go to https://opensciencelabs.org/programs/internship/ or click in Repository link related.
      options:
        - label: scicookie, is a template developed by Open Science Labs that creates projects from project templates and is based on Cookieninja A Cookiecutter Fork command-line utility. [Repository](https://github.com/osl-incubator/scicookie)
        - label: makim, is based on make and focus on improve the way to define targets and dependencies. Instead of using the Makefile format, it uses yaml format [Repository](https://github.com/osl-incubator/makim)
        - label: containers-sugar. The idea of this project is to organize your stack of containers, gathering some useful scripts and keeping this information centralized in a configuration file. So the command line would be very simple. [Repository](https://github.com/osl-incubator/containers-sugar)
        - label: github-actions-chatgpt-pr-reviewer. This GitHub actions uses OpenAI ChatGPT in order to review the changes presented in a PR and will recommend improvements. [Repository](https://github.com/osl-incubator/github-actions-chatgpt-pr-reviewer)
        - label: semantic-release-pr-title-check. Checks for Angular commit message format in the Pull Request Title. [Repository](https://github.com/osl-incubator/semantic-release-pr-title-check)
        - label: satellite-weather-downloader, is a system for downloading, transforming and analysing Copernicus weather data using Xarray. It consists in two major apps, satellite_downloader and satellite_weather. [Repository](https://github.com/osl-incubator/satellite-weather-downloader)
        - label: CrawlClima. This package contains the PEGATWEETS and PEGATEMPERATURA modules for automatically capturing tweets and weather data. [Repository](https://github.com/osl-incubator/CrawlClima)
        - label: dowloader-app. A shapefiles downloader. [Repository](https://github.com/osl-incubator/downloader-app)
        - label: conda-forge-warning. Conda-Forge Warning aims to present conda-forge package without maintenance. [Repository](https://github.com/osl-incubator/conda-forge-warning)
        - label: pyreaddbc, is a Python library for working with DBase database file. Legacy systems from the Brazilian Ministry of Health still uses DBF and DBC formats to Publicize data. [Repository](https://github.com/osl-incubator/pyreaddbc)
        - label: ghreport. A GitHub Report tool. [Repository](https://github.com/osl-incubator/ghreport)
        - label: gh-check-pr-is-updated. This GitHub actions aims to check if the current PR's branch is updated on top of the upstream branch. [Repository](https://github.com/osl-incubator/gh-check-pr-is-updated)
        - label: github-actions-self-hosted-runner. Dockerfile for the creation of a GitHub Actions runner image to be deployed dynamically. [Repository](https://github.com/osl-incubator/github-actions-self-hosted-runner)
        - label: fqlearn. A graphic solver tool to teach mass transfer and thermodynamics.[Repository](https://github.com/osl-pocs/mass-transfer-py)
        - label: pydatastructs. A project that aims to be a Python package for various data structures and algorithms (including their parallel implementations).[Repository](https://github.com/codezonediitj/pydatastructs/)
        
  - type: checkboxes
    id: coc-accepting
    attributes:
      label: Code of Conduct
      description: Accept the Code of Conduct
      options:
        - label: I have read the [Code of Conduct](https://opensciencelabs.github.io/coc/coc-es.html) and I agree.
          required: true

