name: Aplicar para ser Colaborador/a
description: Application form to request to be a collaborator in OSL
title: "NEW CONTRIBUTOR: <INFORME TU NOMBRE AQUÍ>"
labels: [new-collaborator]
assignees: EverVino, xmnlab
body:
  - type: markdown
    attributes:
      value: |
        Estamos muy felices en tu interés en aportar a la comunidad de Open Science Labs
        y ayudar a muchas personas en todo el mundo.

        Para aplicar para ser colaborador/a en nuestra comunidad, por favor, llene este formulário.

        **Notas**:
        - nuestra comunidad está en discord: https://opensciencelabs.org/discord
        - agrega nuestro calendario público de nuestras reuniones semanales a tu google calendar:
          https://opensciencelabs.org/calendar

  - type: input
    id: email
    attributes:
      label: E-mail
      description: E-mail
      placeholder: ej. email@example.com
    validations:
      required: true

  - type: input
    id: name-full
    attributes:
      label: Nombre Completo
      description: Nombre Completo
    validations:
      required: true

  - type: input
    id: url-linkedin
    attributes:
      label: URL perfil Linkedin
      description: URL del perfil en Linkedin
    validations:
      required: false

  - type: input
    id: url-twitter
    attributes:
      label: URL perfil Twitter
      description: URL del perfil en Twitter
    validations:
      required: false

  - type: input
    id: url-github
    attributes:
      label: URL perfil GitHub
      description: URL del perfil en GitHub
    validations:
      required: false

  - type: input
    id: url-photo
    attributes:
      label: URL de foto de perfil
      description: URL del perfil par ser usada en la página de mentores/as
    validations:
      required: true

  - type: input
    id: languages
    attributes:
      label: Idiomas
      description: Informe los idiomas que sabes
      multiple: true
      options:
        - Español
        - Inglés
        - Portugués
        - Francés
    validations:
      required: true

  - type: textarea
    id: bio
    attributes:
      label: Bio
      description: resumen sobre ti, similar a uno publicado en Linkedin o CV
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: ¿Por qué quiero colaborar a la comunidad OSL?
      description: resumen sobre porqué quieres colaborar a la comunidad OSL
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Área de interés
      description: ¿En qué áreas te gustaría colaborar?
      multiple: true
      options:
        - DevOps
        - Creación de Artículos (blog)
        - Producción de Videos (youtube)
        - Community Management
        - Social Media
        - Diversidad, Equidad e Inclusión
        - Organización de Eventos
        - Documentación
        - Mentoría
        - Gestión de Proyectos
        - Fund raising
    validations:
      required: true

  - type: dropdown
    id: availability
    attributes:
      label: Horas semanales disponibles para dedicarme a la comunidad OSL
      description: Horas semanales disponibles para dedicarme a la comunidad OSL
      options:
        - 2 horas semanales
        - 4 horas semanales
        - 6+ horas semanales
    validations:
      required: true

  - type: checkboxes
    id: coc-accepting
    attributes:
      label: Código de Conducta
      description: Aceptar Código de Conducta
      options:
        - label: He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo
          required: true

  - type: checkboxes
    id: mentoring-guide-reading
    attributes:
      label: Guía de Mentorías
      description: Leer guía de mentorías
      options:
        - label: He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)
          required: true
