name: Aplicar para ser Mentores/as en OSL
description: Request Form for new mentors
title: "New Mentor: <INFORME TU NOMBRE AQUÍ>"
labels: [new-mentor]
assignees: EverVino, xmnlab
body:
  - type: markdown
    attributes:
      value: |
        Para aplicar para ser mentor/a de nuestra comunidad, por favor, llene este formulário.
        Notas:
        - nuestra comunidad está en discord:  http://discord.opensciencelabs.org
        - agrega nuestro calendario público de nuestras reuniones semanales a tu google calendar:
          http://calendar.opensciencelabs.org

  - type: input
    id: email
    attributes:
      label: E-mail
      description: E-mail
      placeholder: ej. email@example.com
    validations:
      required: true

  - type: input
    id: name-full
    attributes:
      label: Nombre Completo
      description: Nombre Completo
    validations:
      required: true

  - type: input
    id: url-linkedin
    attributes:
      label: URL perfil Linkedin
      description: URL del perfil en Linkedin
    validations:
      required: false

  - type: input
    id: url-twitter
    attributes:
      label: URL perfil Twitter
      description: URL del perfil en Twitter
    validations:
      required: false

  - type: input
    id: url-github
    attributes:
      label: URL perfil GitHub
      description: URL del perfil en GitHub
    validations:
      required: false

  - type: input
    id: url-photo
    attributes:
      label: URL de foto de perfil
      description: URL del perfil par ser usada en la página de mentores/as
    validations:
      required: true

  - type: textarea
    id: bio
    attributes:
      label: Bio
      description: resumen sobre ti, similar a uno publicado en Linkedin o CV
    validations:
      required: true

  - type: input
    id: areas
    attributes:
      label: Áreas de interés para las mentorías
      description: Informe las áreas de interés para las mentorías separadas por coma
    validations:
      required: true

  - type: input
    attributes:
      label: Idiomas disponible para las mentorías
      description: Informe los idiomas en los cuales puedes dar las mentorías
    validations:
      required: true

  - type: checkboxes
    id: coc-accepting
    attributes:
      label: Código de Conducta
      description: Aceptar Código de Conducta
      options:
        - label: He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo
          required: true

  - type: checkboxes
    id: mentoring-guide-reading
    attributes:
      label: Guía de Mentorías
      description: Leer guía de mentorías
      options:
        - label: He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)
          required: true
