name: OSL Internship Program 2024 (1st Cycle) - Project Ideas Submission
description: Submit your project ideas for the OSL Internship Program 2024 (1st Cycle)
title: "OSL Internship Program 2024-01 (Orgs/Projects): [Enter your organization/project name here]"
labels: [internship, internship-2024-1, internship-project]
assignees: EverVino, xmnlab
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the submission form for project ideas for the OSL
        Internship Program 2024 (1st Cycle).

        Please ensure you are a core maintainer of the projects you wish to submit.
        Begin by reviewing the Internship Program documentation:
          https://opensciencelabs.org/programs/internship/

        Your projects must adhere to a Code of Conduct and be licensed under an
        OSI-approved open-source license (https://opensource.org/licenses/).

        Refer to this document for guidance on filling out this form:
        https://github.com/OpenScienceLabs/grant-proposals/blob/main/gsoc/2023/osl-projects-ideas.md
        (used for GSoC project idea submissions).

        If you have any questions, reach out to us on Discord.

        Connect with us:
        - Join our Discord server: https://opensciencelabs.org/discord
        - Follow us on social media:
          - Twitter: https://twitter.com/opensciencelabs
          - YouTube: https://www.youtube.com/@opensciencelabs
          - LinkedIn: https://www.linkedin.com/company/open-science-labs

  - type: input
    id: organization_name
    attributes:
      label: Organization/Project Name
      description: Enter the name of your organization or project.
      placeholder: "e.g., My Organization Name"
    validations:
      required: true

  - type: input
    id: organization_url
    attributes:
      label: Organization/Project Webpage URL
      description: Provide the URL of your organization or project's webpage.
      placeholder: "e.g., http://www.myorganization.com"
    validations:
      required: true

  - type: textarea
    id: organization_intro
    attributes:
      label: Organization/Project Introduction
      description: Write a short introduction about your organization or project.
    validations:
      required: true

  - type: textarea
    id: organization_summary
    attributes:
      label: Organization/Project Summary
      description: |
        Detail the purpose, usage, and key aspects of your organization or project.
        Include details like mission, goals, and key activities.
    validations:
      required: true

  - type: textarea
    id: organization_organization
    attributes:
      label: Organization/Project Structure
      description: |
        Describe the internal structure, members, and target audience of your organization or project.
        Include information on organizational hierarchy, member roles, and audience demographics.
    validations:
      required: true

  - type: input
    id: applicant_name
    attributes:
      label: Applicant's Full Name
      description: Provide your full name.
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Applicant's Email
      description: Enter your email address.
      placeholder: e.g., email@example.com
    validations:
      required: true

  - type: checkboxes
    id: coc_accepting
    attributes:
      label: Code of Conduct Agreement
      description: Confirm your agreement with the Code of Conduct.
      options:
        - label: |
            I have read and agree to the
            [Code of Conduct](https://opensciencelabs.org/guidelines/coc/).
    validations:
      required: true

  - type: input
    id: project_idea_url
    attributes:
      label: Project Ideas Document Link
      description: |
        Provide the URL for your project ideas proposal document. Refer to this
        [example](https://opensciencelabs.org/programs/internship/templates/projects-ideas/)
        for guidance.
    validations:
      required: true
