name: Solicitud de Mentoría
description: Mentoring request
title: "Solicitud de mentoría: <INFORME TU NOMBRE AQUÍ>"
labels: [mentoring-request]
assignees: EverVino, xmnlab
body:
  - type: markdown
    attributes:
      value: |
        Si quieres solicitar mentoría, por favor, llene este formulário.
        Notas:
        - nuestra comunidad está en discord:  https://opensciencelabs.org/discord

  - type: input
    id: email
    attributes:
      label: E-mail
      description: E-mail
      placeholder: ej. email@example.com
    validations:
      required: true

  - type: input
    id: name-full
    attributes:
      label: Nombre Completo
      description: Nombre Completo
    validations:
      required: true

  - type: input
    id: mentors
    attributes:
      label: Las(os) Mentoras(os)
      description: Informe al menos 2 mentoras(es) que te interesaría tener soporte. Verifique en la [lista completa](https://opensciencelabs.org/mentoring/mentors/) si los/las mentores/as tienen disponibilidad.
      placeholder: ej. Ivan y Evelyn
    validations:
      required: true

  - type: textarea
    id: mentoring
    attributes:
      label: Expectativas
      description: Cuéntenos un poco sobre sus expectativas sobre la tutoría y lo que espera lograr.
    validations:
      required: true

  - type: input
    id: schedule
    attributes:
      label: Horario de la Primera Reunión
      description: ¿Cuál sería el mejor momento para la primera reunión?
      placeholder: ej. Lunes 9AM UTC-4
    validations:
      required: true

  - type: input
    id: url-linkedin
    attributes:
      label: URL perfil Linkedin
      description: URL del perfil en Linkedin
    validations:
      required: false

  - type: input
    id: url-twitter
    attributes:
      label: URL perfil Twitter
      description: URL del perfil en Twitter
    validations:
      required: false

  - type: input
    id: url-github
    attributes:
      label: URL perfil GitHub
      description: URL del perfil en GitHub
    validations:
      required: false

  - type: checkboxes
    id: coc-accepting
    attributes:
      label: Código de Conducta
      description: Aceptar Código de Conducta
      options:
        - label: He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo
          required: true

  - type: checkboxes
    id: mentoring-guide-reading
    attributes:
      label: Guía de Mentorías
      description: Leer guía de mentorías
      options:
        - label: He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)
          required: true
